### ISSUE TITLE
Network formation: Network joining

### ISSUE THREAD

**Issue by SpiffiRacoon** [SpiffiRacoon/group-12-kadlab#3]
M1.
Network formation. **[5p]**. Your nodes must be able to form networks as described in the Kademlia paper. Kademlia is a protocol for facilitating Distributed Hash Tables (DHTs). Concretely, the following aspects of the algorithm must be implemented:
(b) **Network joining**. Given the IP address, and any other data you decide, of any single
node, a node must be able to join or form a network with that node.

**Comment by TovahParnes** [comment]
Completed this in the branch connected to issue 7: https://github.com/SpiffiRacoon/group-12-kadlab/issues/7
